[template]
src = "application.properties.conf.tmpl"
dest = "./src/main/resources/application.properties"
keys = [
    "/xpresso/database/name",
    "/xpresso/database/username",
    "/xpresso/database/password",
    "/xpresso/database/host",
    "/xpresso/database/port",
]